name: Wake Time

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches: [ master ]

jobs:
  update-readme:
    name: WakaReadme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          SHOW_TITLE: true
          TIME_RANGE: all_time
          SHOW_MASKED_TIME: true
          BLOCKS: ->
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
